# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loc1seasonal_c <- function(params, loc1seasonal_var) {
    .Call(`_priceT_loc1seasonal_c`, params, loc1seasonal_var)
}

sigma_c <- function(sresids) {
    .Call(`_priceT_sigma_c`, sresids)
}

create_sequence <- function(start, end) {
    .Call(`_priceT_create_sequence`, start, end)
}

Fourier_cpp <- function(residuals, station, start_ind, end_ind, type, seasonal_coefs) {
    .Call(`_priceT_Fourier_cpp`, residuals, station, start_ind, end_ind, type, seasonal_coefs)
}

cos_approx <- function(x) {
    .Call(`_priceT_cos_approx`, x)
}

loc1temp_c <- function(params, t, loc1temperatures) {
    .Call(`_priceT_loc1temp_c`, params, t, loc1temperatures)
}

loc1optim <- function(initial, t, loc1temperatures) {
    .Call(`_priceT_loc1optim`, initial, t, loc1temperatures)
}

seasonal_cpp <- function(temp) {
    .Call(`_priceT_seasonal_cpp`, temp)
}

