# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loc1seasonal_c <- function(params, loc1seasonal_var) {
    .Call(`_priceT_loc1seasonal_c`, params, loc1seasonal_var)
}

sigma_c <- function(sresids) {
    .Call(`_priceT_sigma_c`, sresids)
}

create_sequence <- function(start, end) {
    .Call(`_priceT_create_sequence`, start, end)
}

Fourier_cpp <- function(residuals, station, start_ind, end_ind, type, seasonal_coefs) {
    .Call(`_priceT_Fourier_cpp`, residuals, station, start_ind, end_ind, type, seasonal_coefs)
}

obj_cpp <- function(theta, market_price, residuals, station, start_ind, end_ind, type, seasonal_coefs, func) {
    .Call(`_priceT_obj_cpp`, theta, market_price, residuals, station, start_ind, end_ind, type, seasonal_coefs, func)
}

calib_cpp <- function(market_price, residuals, station, start_ind, end_ind, type, seasonal_coefs, func, learning_rate = 0.1, max_iter = 1000L, tol = 1e-6, theta_min = -50.0, theta_max = 50.0) {
    .Call(`_priceT_calib_cpp`, market_price, residuals, station, start_ind, end_ind, type, seasonal_coefs, func, learning_rate, max_iter, tol, theta_min, theta_max)
}

cos_approx <- function(x) {
    .Call(`_priceT_cos_approx`, x)
}

loc1temp_c <- function(params, t, loc1temperatures) {
    .Call(`_priceT_loc1temp_c`, params, t, loc1temperatures)
}

loc1optim <- function(initial, t, loc1temperatures) {
    .Call(`_priceT_loc1optim`, initial, t, loc1temperatures)
}

seasonal_cpp <- function(temp) {
    .Call(`_priceT_seasonal_cpp`, temp)
}

