# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cos_approx <- function(x) {
    .Call(`_priceT_cos_approx`, x)
}

loc1temp <- function(params, t, loc1temperatures) {
    .Call(`_priceT_loc1temp`, params, t, loc1temperatures)
}

loc1optim <- function(initial, t, loc1temperatures) {
    .Call(`_priceT_loc1optim`, initial, t, loc1temperatures)
}

seasonal_cpp <- function(temp) {
    .Call(`_priceT_seasonal_cpp`, temp)
}

